[Audio]
description = "Installs and sets up the PipeWire audio system."

[Aur]
description = "AUR (Arch User Repository) is a community-driven repository for Arch Linux users, containing user-submitted package build scripts (PKGBUILDs) that make it easy to install software not available in the official repositories. The script will let you choose an AUR helper and install it according to your preference."

[AutoLogin-TTY]
description= "The script will give you two options: either to enable autologin in TTY or to remove it later if you need to after enabling. Btw, I do not recommend enabling this, as anyone can have physical access without your username and password."

[Bluetooth]
description = "Installs Bluetooth packages and sets up Bluetooth functionality."

[Brightness]
description = "Sets screen brightness to your preference using Brightnessctl."

["Chaotic-Aur"]
description = "Chaotic-AUR is a popular unofficial Arch User Repository (AUR) helper repository providing prebuilt binary packages. The script installs Chaotic-AUR and configures `pacman.conf` to use it."

[Fastfetch]
description = "Fastfetch is a lightweight system information tool displaying OS, hardware, and other details in a clean, customizable format. The script applies my fastfetch config from the harilvfs/fastfetch repo."

[Fonts]
description = "Downloads and installs a variety of Nerd Fonts for improved readability and aesthetics in terminal applications."

[Grub]
description = "GRUB (GNU GRand Unified Bootloader) is a bootloader that lets you choose and load operating systems or kernels on startup. The script offers various themes and applies necessary GRUB configurations. Credit to chrisTitusTech/Top-5-Bootloader-Themes for the themes and script assistance."

["LTS-Kernel"]
description = "This script installs the LTS kernel for Arch-based distros only (not for Fedora or openSUSE)."

[Packages]
description = "Provides a menu with various package categories like Android tools, browsers, multimedia, development, and more. Most widely used packages are included, with additional packages coming in future updates."

[Sddm]
description = "SDDM (Simple Desktop Display Manager) is a modern, Qt-based graphical login manager. The script installs a Catppuccin-based theme for SDDM from the Catppuccin community."
